version: '3.8'

services:
# mongo Primary replica set
  mongo01:
    image: mongo
    container_name: mongo01
    command: mongod --replSet replica01 --bind_ip_all
    depends_on:
      - mongo02
      - mongo03
      - mongo04
      - mongo05
    ports:
      - "27017:27017"
    networks:
      - red01
# mongo replica
  mongo02:
    image: mongo
    container_name: mongo02
    command: mongod --replSet replica01 --bind_ip_all
    ports:
      - "27018:27017"
    networks:
      - red01
# mongo replica
  mongo03:
    image: mongo
    container_name: mongo03
    command: mongod --replSet replica01 --bind_ip_all
    ports:
      - "27019:27017"
    networks:
      - red01
# mongo replica
  mongo04:
    image: mongo
    container_name: mongo04
    command: mongod --replSet replica01 --bind_ip_all
    ports:
      - "27020:27017"
    networks:
      - red01
# mongo replica
  mongo05:
    image: mongo
    container_name: mongo05
    command: mongod --replSet replica01 --bind_ip_all
    ports:
      - "27021:27017"
    networks:
      - red01
# redis logger
  redis01:
    image: redis
    container_name: redis01
    ports:
      - "6379:6379"
    networks:
      - red01
    depends_on:
      - mongo01

# build node app
  mongoose-replicaset01:
    # build: .
    image: mongoose-replicaset01
    container_name: mongoose-replicaset01
    depends_on:
      - redis01
      - mongo01
    environment:
      - MONGO_URI=mongodb://mongo01,mongo02,mongo03,mongo04,mongo05/?replicaSet=replica01
      - DATABASE=tecnologico
      - REDIS_HOST=redis01
      - REDIS_PORT=6379
    ports:
      - "3000:3000"
    networks:
      - red01
    restart: unless-stopped
  
networks:
  red01:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24